version: 2
updates:
  - package-ecosystem: 'cargo'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'improvement'
    reviewers:
      - 'slavik-pastushenko'
    assignees:
      - 'slavik-pastushenko'
