[package]
name = "blockchain-cli"
description = "Provides a command-line interface (CLI) for interacting with blockchain"
version = "1.0.8"
edition = "2021"
license = "MIT"
readme = "README.md"
authors = ["Slavik Pastushenko <slavpas@gmail.com>"]
keywords = ["cli", "crypto", "blockchain"]
exclude = [".prettierrc.toml", ".github/**"]
categories = ["command-line-utilities", "cryptography"]
documentation = "https://docs.rs/blockchain-cli"
repository = "https://github.com/slavik-pastushenko/blockchain-rust"

[lib]
name = "blockchain"
path = "src/lib.rs"

[[bin]]
name = "blockchain-prompts"
path = "src/bin/blockchain.rs"

[features]
coverage = []

[dependencies]
chrono = "0.4.31"
cliclack = "0.1.9"
serde = { version = "1.0.192", features = ["derive"] }
serde_derive = "1.0.192"
serde_json = "1.0.108"
sha2 = "0.10.8"
