pre-release-commit-message = "{{crate_name}} {{version}}"
pre-release-hook = [
  "git",
  "cliff",
  "-o",
  "CHANGELOG.md",
  "--tag",
  "{{version}}",
]
allow-branch = ["main"]
tag-message = "chore: release v{{version}}"
