[package]
name = "blockchain-cli-examples"
version = "0.0.0"
edition = "2021"
publish = false

[[bin]]
name = "blockchain-prompts"
path = "src/main.rs"

[dependencies]
blockchain-cli = { path = ".." }
cliclack = "0.1.9"
