name: publish

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: stable

    - name: Install cargo-release
      run: cargo install cargo-release

    - name: Publish to crates.io
      env:
        CRATE_NAME: blockchain-cli
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: |
        # Set
        git config --global user.email "slavpas@gmail.com"
        git config --global user.name "Slavik Pastushenko"

        # Bump the version and create a GitHub release
        cargo release --execute --no-confirm patch
