name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: stable

    - name: Install cargo-release
      run: cargo install cargo-release

    - name: Bump version and create GitHub release
      run: |
        # Bump the version and create a GitHub release
        cargo release

        # Get the version number from Cargo.toml
        VERSION=$(grep -oP 'version = "\K[^"]+' Cargo.toml)

        # Create a GitHub release using the GitHub CLI
        gh release create "v$VERSION" target/package/blockchain-cli-*.crate -t "v$VERSION"
      env:
        CRATE_NAME: blockchain-cli

    - name: Publish to crates.io
      run: cargo publish
      env:
        CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
