name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install tarpaulin
      run: cargo install cargo-tarpaulin
    - name: Build
      run: cargo build --verbose
    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Run lint
      run: cargo fmt -- --check
    - name: Run tests
      run: cargo tarpaulin --lib --out xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        file: ./cobertura.xml
